# Generated by Django 5.2.6 on 2025-10-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0004_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(max_length=255)),
                ('hero_subtitle', models.TextField()),
                ('hero_image', models.ImageField(upload_to='hero/')),
                ('services', models.JSONField(help_text='List of services with title, description, and image')),
                ('why_title', models.CharField(default='Why choose us?', max_length=255)),
                ('why_description', models.TextField()),
                ('why_images', models.JSONField(help_text='List of images for why choose us section')),
                ('stats', models.JSONField(help_text='List of statistics with title, value, and icon')),
            ],
        ),
    ]
