# Generated by Django 5.2.6 on 2025-10-01 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0006_homebanner_homeservice_homestat_delete_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeWhyChooseUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='home/')),
                ('heading', models.CharField(default='Why choose us?', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('stat1_title', models.CharField(default='Years of Industry Experience', max_length=100)),
                ('stat1_value', models.CharField(default='50+', max_length=50)),
                ('stat1_desc', models.TextField(default='Combining decades of expertise to provide reliable, effective electrical solutions.')),
                ('stat2_title', models.CharField(default='Projects Completed', max_length=100)),
                ('stat2_value', models.CharField(default='5000+', max_length=50)),
                ('stat2_desc', models.TextField(default='Reflecting the trust businesses and home owners place in us for ongoing electrical services.')),
                ('stat3_title', models.CharField(default='First-Time Fix Rate', max_length=100)),
                ('stat3_value', models.CharField(default='98%', max_length=50)),
                ('stat3_desc', models.TextField(default='Proving our efficiency in diagnosing and resolving electrical issues on the first visit.')),
                ('stat4_title', models.CharField(default='Client Energy Savings', max_length=100)),
                ('stat4_value', models.CharField(default='10M', max_length=50)),
                ('stat4_desc', models.TextField(default='Estimating the financial impact our solutions have had in reducing energy costs.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='HomeStat',
        ),
    ]
