# Generated by Django 5.2.6 on 2025-10-01 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0007_homewhychooseus_delete_homestat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home1Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Brand Name', max_length=200)),
                ('logo', models.ImageField(upload_to='home1/brands/')),
                ('website', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Home1ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Get in Touch with Electric Dreams Electrical Today', max_length=200)),
                ('phone', models.CharField(default='+91 1234567890', max_length=20)),
                ('button_text', models.CharField(default='Call Us Today', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Home1FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='FAQ Question?', max_length=255)),
                ('answer', models.TextField(default='Default FAQ answer goes here.')),
            ],
        ),
        migrations.CreateModel(
            name='Home1Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Step Title', max_length=200)),
                ('description', models.TextField(default='Step description here...')),
                ('order', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Home1Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Customer Name', max_length=200)),
                ('role', models.CharField(default='Service Type', max_length=200)),
                ('feedback', models.TextField(default='Customer feedback goes here...')),
                ('stars', models.PositiveIntegerField(default=5)),
            ],
        ),
    ]
