# Generated by Django 5.2.6 on 2025-10-01 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0008_home1brand_home1contactinfo_home1faq_home1step_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Professional Emergency Electrician - Fast & Reliable', max_length=255)),
                ('subtitle', models.TextField(default='24-hour Electrician in Electric town. Call Our Professional Electricians Now to Get Help Fast')),
                ('button_text', models.CharField(default='Get Emergency Service', max_length=50)),
                ('image', models.ImageField(upload_to='emergency/banners/')),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyCallToAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Get in Touch with Electric Dreams Electrical Today', max_length=255)),
                ('phone', models.CharField(default='+1234567890', max_length=20)),
                ('button_text', models.CharField(default='Call Now', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyFormContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Request a call back', max_length=255)),
                ('description', models.TextField(default='Fill in your details below and we will get back to you within 30 minutes or less')),
                ('name_placeholder', models.CharField(default='Name', max_length=50)),
                ('mobile_placeholder', models.CharField(default='Mobile', max_length=50)),
                ('email_placeholder', models.CharField(default='Email address', max_length=50)),
                ('service_placeholder', models.CharField(default='Service', max_length=50)),
                ('submit_text', models.CharField(default='Send Message', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='emergency/icons/')),
                ('title', models.CharField(default='Lifetime Warranty', max_length=100)),
                ('description', models.TextField(default='We provide high-quality services with lifetime warranty.')),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyWhyChoose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Quality Workmanship', max_length=255)),
                ('description', models.TextField(default='Our electricians are trained and experienced to handle all emergencies efficiently.')),
                ('image', models.ImageField(upload_to='emergency/why_choose/')),
            ],
        ),
    ]
