# Generated by Django 5.2.6 on 2025-10-01 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0009_emergencybanner_emergencycalltoaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Electric Dreams', max_length=200)),
                ('description', models.TextField(default='We are here to provide tailored solutions that meet your unique electrical needs.')),
                ('contact_number', models.CharField(default='+911234567890', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AboutImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='AboutCommitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Our Commitment to You', max_length=200)),
                ('description', models.TextField(default='At Electric Dreams Solutions Group, client satisfaction isn’t just a goal...')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='about_commitment_image', to='coreapp.aboutimage')),
            ],
        ),
        migrations.CreateModel(
            name='AboutService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='about_service_image', to='coreapp.aboutimage')),
            ],
        ),
        migrations.CreateModel(
            name='AboutWhoWeAre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Who we are ?', max_length=200)),
                ('description', models.TextField(default='Electric Dreams Group was founded with a passion for powering the community responsibly...')),
                ('license_info', models.TextField(default='Electrical Contractors License: 12356\nSolar Accreditation: 5762397')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='about_who_we_are_image', to='coreapp.aboutimage')),
            ],
        ),
    ]
