# Generated by Django 5.2.6 on 2025-10-01 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0010_aboutcompanyinfo_aboutimage_aboutcommitment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPageForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='First Name', max_length=100)),
                ('last_name', models.CharField(blank=True, default='Last Name', max_length=100)),
                ('phone_placeholder', models.CharField(default='Phone number', max_length=100)),
                ('email_placeholder', models.CharField(default='Email address', max_length=100)),
                ('address_placeholder', models.CharField(default='Address (Optional)', max_length=200)),
                ('message_placeholder', models.CharField(default='Type your message...', max_length=200)),
                ('button_text', models.CharField(default='Send Message', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ContactPageInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Contact Us', max_length=200)),
                ('subtitle', models.CharField(default='We’d love to hear from you.', max_length=300)),
                ('phone_label', models.CharField(default='Call our Team', max_length=100)),
                ('phone_number', models.CharField(default='+91-1234567890', max_length=50)),
                ('email_label', models.CharField(default='Reach out to us', max_length=100)),
                ('email_address', models.EmailField(default='support@electricdreams.com', max_length=254)),
                ('map_image', models.ImageField(blank=True, null=True, upload_to='contactpage/')),
            ],
        ),
    ]
