# Generated by Django 5.2.6 on 2025-10-01 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0011_contactpageform_contactpageinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_title', models.CharField(default='Areas we services', max_length=200)),
                ('area_subtitle', models.TextField(default='Below are some areas we provide electrical services to. But, don’t worry if your area is not listed, we likely service your area too!')),
                ('area_cta_text', models.CharField(default='Get in Touch with Electric Dreams Electrical Today', max_length=200)),
                ('area_cta_button_text', models.CharField(default='Call(+91)1234567890', max_length=50)),
                ('area_cta_button_link', models.CharField(default='tel:+911234567890', max_length=100)),
                ('area_image', models.ImageField(blank=True, null=True, upload_to='areas/')),
            ],
        ),
        migrations.CreateModel(
            name='AreaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='coreapp.areasection')),
            ],
        ),
    ]
